import { ReactNode } from "react";
import NavBar from "./NavBar";
import { Metadata } from "next";

interface Props {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Boiler PLate - Home",
  description: "Generated by create next app",
};
const HomeLayout = ({ children }: Props) => {
  return (
    <div className="h-dvh w-dvw overflow-auto">
      <header className="w-full min-h-15 bg-(--background) shadow flex flex-col justify-between items-center z-50">
        <NavBar />
      </header>
      <main className="h-9/10 w-full px-35">{children}</main>
    </div>
  );
};

export default HomeLayout;
